server:
  port: 8000

logging:
  level:
#    root: INFO
    root: DEBUG
    org.hibernate: INFO

spring:
  jpa:
    defer-datasource-initialization: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
#    username: sa
#    password: password
  artemis:
    mode: embedded

notify-service:
  url: http://localhost:8000/notify

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

scheduling:
  enabled: false