server:
  port: 8000

spring:
  jpa:
    defer-datasource-initialization: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false

notify-service:
  url: http://localhost:8000/notify