server:
  port: 8000

logging:
  level:
    root: INFO
#    root: DEBUG
    org:
      hibernate: INFO
#      springframework: DEBUG
#        vault: DEBUG

spring:
  cloud:
    vault:
      token: root
      uri: http://localhost:8200
  jpa:
    defer-datasource-initialization: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
#    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: changeme
  artemis:
    mode: embedded
  kafka:
    producer:
      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.JsonSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-loggers
      auto-offset-reset: earliest
#    template:
#      default-topic: my-topic
    bootstrap-servers: localhost:9092

kafka:
  topic-name-string: my-topic-string
  topic-name-object: my-topic-object
  stream-input-topic: input-topic
  stream-output-topic: output-topic
  stream-filtered-topic: filtered-topic
  messages-per-request: 10

notify-service:
  url: http://localhost:8000/notify

elasticsearch:
  url: localhost:9200
  api-key: REtYMjBaVUJBUHh0SF9lU3ZNSm06UmFUaF9uR1pUOHFwZ2c1eDg1STVxdw==

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

scheduling:
  enabled: false