services:
  vault:
    image: hashicorp/vault:latest
    container_name: ${VAULT_LOCAL_CONTAINER_NAME}
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "http://localhost:8200"
      VAULT_DEV_LISTEN_ADDRESS : "vault:8200"
    privileged: true
